### PR TITLE
Docker multiarch build update

### PR DESCRIPTION
**Pull request by benbierens**

### CODE REVIEW

**Comment by veaceslavdoina** [comment]
CI related stuff looks good.

Thanks!

**Comment by veaceslavdoina** [comment]
We at least need CI/Docker related code.

@benbierens what about other changes?

**Comment by veaceslavdoina** [comment]
I just created #461 

So, CI part will be added separately and if do not need this PR, we can close it.

**Comment by veaceslavdoina** [comment]
@benbierens, CI related part was merged. If we do not need other changes in this PR, we may close it.

**Comment by benbierens** [comment]
Yes, all of these changes have found their way via their own PRs. Closing this one!

**Pull request closed without merging**
