### PR TITLE
Multi-node integration test refactor

### PR DESCRIPTION
**Pull request by emizzle**
Refactoring of the multi node integration tests, into a `marketplacetestsuite`. Allows us to run many node integration tests on our local machine, which saves quite a lot of time as compared to the distributed tests.

Notable features:
- Allows arbitrary number of nodes for `clients`, `providers`, and `validators`.
- Allows log files for each started node to be captured (including hardhat), saved in `tests/integration/logs/<start_datetime> <suite_name>/<test_name>/<node_role>_<node_idx>.log`.
- Allows log topics to be specified
- Allows simulation of proof failures to be specified
- Allows log output to stdout

Two notable changes:
1. `OnChainClock.now` was changed so that it always get the time from the last block time. Without this change, the clock was drifting from the actual last block time, which was causing validators to mark proofs as missing when not required, or not mark them missing when required, and providers were sending proofs when the period had not yet ended. Once the change was in, these errors disappeared.
2. Cancellation of the `SaleProving` prove loop was removed as it was hanging during integration tests. This is not needed as the state machine will cancel `SaleProving.run`, of which the `proveLoop` is a child and should also be cancelled.

Leaving this in draft for now as I'd like to try moving the node config setup into each test, as opposed to being defined at the suite-level.

### CODE REVIEW

**Review by markspanbroek — COMMENTED** [review]
The multinodesuite looks good to me. Also includes a lot of changes that are not related to integration testing, but they look good too.

However, the tests fail on my machine, and they didn't run in CI for some reason.

```
[Suite] Simulate invalid proofs
    /home/user/development/nim-codex/tests/integration/testproofs.nim(104, 21): Check failed: eventually client0.purchaseStateIs(purchaseId, "started")
    /home/user/development/nim-codex/tests/integration/testproofs.nim(115, 21): Check failed: eventuallyP(slotWasFreed, currentPeriod + totalPeriods.u256 + 1)
  [FAILED] slot is freed after too many invalid proofs submitted
  [OK] slot is not freed when not enough invalid proofs submitted
    /home/user/development/nim-codex/tests/integration/testproofs.nim(243, 21): Check failed: eventually provider1.node.client.saleStateIs(provider1slotId, "SaleProving")
    /home/user/development/nim-codex/tests/integration/testproofs.nim(245, 21): Check failed: eventually client0.purchaseStateIs(purchaseId, "started")
    /home/user/development/nim-codex/tests/integration/testproofs.nim(248, 21): Check failed: eventuallyP(provider0.node.client.saleStateIs(provider0slotId, "SalePayout"),
            currentPeriod + totalPeriods.u256 + 1)
    /home/user/development/nim-codex/tests/integration/testproofs.nim(253, 21): Check failed: eventuallyP(provider1.node.client.saleStateIs(provider1slotId, "SalePayout"),
            currentPeriod + totalPeriods.u256 + 1)
    /home/user/development/nim-codex/tests/integration/testproofs.nim(258, 20): Check failed: eventually((await token.balanceOf(!provider1.address)) >
    (await token.balanceOf(!provider0.address)))
  [FAILED] host that submits invalid proofs is paid out less
```

**Comment by AuHau** [comment]
Closes https://github.com/codex-storage/nim-codex/issues/594

**Comment by AuHau** [comment]
🎉
image

**Comment by emizzle** [comment]
Closing in favour of https://github.com/codex-storage/nim-codex/pull/662.

**Pull request closed without merging**
