### PR TITLE
WIP: add support for multiple PoR EC backends

### PR DESCRIPTION
**Pull request by cskiraly**
The original code was based on BLST.
This patch extracts a backend interface and adds one more elliptic curve pairing-based cryptography backend: nim-constantine.

 - BLST is audited. It supports the BLS12-381 curve only
 - nim-constantine is more experimental, but it supports both BLS and BN curves

### CODE REVIEW

**Comment by cskiraly** [comment]
WIP as it could still use some improvements:
- better naming on backend interface
- multi-pairing on nim-constantine backend for BN curves

**Comment by cskiraly** [comment]
Compilation on Intel with the Constantine backend currently fails with the following error:

```
nim c -r -d:por_backend_constantine -d:por_curve_bn254 dagger/por/testpor.nim
[...]
CC: ../../../../.nimble/pkgs/constantine-0.0.1/constantine/math/arithmetic/assembly/limbs_asm_modular_x86.nim
/home/cskiraly/.cache/nim/testpor_d/@m..@s..@s..@s..@s.nimble@spkgs@sconstantine-0.0.1@sconstantine@smath@sarithmetic@sassembly@slimbs_asm_modular_x86.nim.c: In function ‘submod_asm__OOZOOZOOZOOZOnimbleZpkgsZconstantine4548O48O49ZconstantineZmathZcurvesZbn50535295nogami95subgroups_1630’:
/home/cskiraly/.cache/nim/testpor_d/@m..@s..@s..@s..@s.nimble@spkgs@sconstantine-0.0.1@sconstantine@smath@sarithmetic@sassembly@slimbs_asm_modular_x86.nim.c:137:47: error: ‘V’ undeclared (first use in this function)
  137 | : [b] "+r" (b), [U2] "+r" (U[2]), [V2] "=&r" (V[2]), [U0] "+r" (U[0]), [V1] "=&r" (V[1]), [U3] "+r" (U[3]), [U1] "+r" (U[1]), [r] "+r" (r), [V0] "=&r" (V[0]), [V3] "=&r" (V[3])
      |                                               ^
/home/cskiraly/.cache/nim/testpor_d/@m..@s..@s..@s..@s.nimble@spkgs@sconstantine-0.0.1@sconstantine@smath@sarithmetic@sassembly@slimbs_asm_modular_x86.nim.c:137:47: note: each undeclared identifier is reported only once for each function it appears in
```

Any ideas? My guess is that the way I'm including internals is breaking something in the compilation.

**Comment by gmega** [comment]
@cskiraly is this still relevant? Can we close it or should we work on it?

**Comment by dryajov** [comment]
closing as this approach is scrapped for now.

**Pull request closed without merging**
