### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by Menduist**
This currently fails for a weird reason:
```
/nim-codex/codex/stores/cachestore.nim(107, 15) template/generic instantiation of `without` from here
/nim-codex/vendor/questionable/questionable/withoutresult.nim(15, 7) Error: typechecked nodes may not be modified
```

Any ideas @markspanbroek?
I tried reverting the bump of questionable & Nim, but this still happens

Requires:
https://github.com/status-im/questionable/pull/32
https://github.com/codex-storage/nim-libp2p-dht/pull/59

### CODE REVIEW

**Comment by markspanbroek** [comment]
I have not seen it before, but I do have an idea where it might be coming from. I'll take a look :eyes:

**Comment by Menduist** [comment]
Well this is taking a lot longer than expected :sweat_smile: I'll let someone else pick this up, sorry about that

**Comment by elcritch** [comment]
Updating this from master branch.

**Comment by elcritch** [comment]
@dryajov I fixed another couple of compile issues that arose after using the patched `questionable` and `nim-libp2p-dht` libraries.

**Comment by dryajov** [comment]
closing as it was addressed by #492

**Pull request closed without merging**
