### PR TITLE
update asynctest to 0.5.1

### PR DESCRIPTION
**Pull request by markspanbroek**

### CODE REVIEW

**Review by dryajov — APPROVED** [review]
LGTM, but why do we need to import `chronos/unittest` explicitely?

**Comment by markspanbroek** [comment]
> why do we need to import `chronos/unittest` explicitly

Good question. The asynctest code became rather hard to maintain, because it consisted of code that just happened to be compatible with both chronos and asynctest. This already lead to unwanted warnings in some cases, and became even harder to maintain with the recent chronos changes w.r.t. exceptions. The solution was to have different code for asynctest and chronos, but that requires an explicit choice when importing asynctest (https://github.com/codex-storage/asynctest/pull/11).

**Review by dryajov — APPROVED** [review]
Lets get this one merged as well, regardless of it being in #673

**Comment by gmega** [comment]
Yeah, that's probably wise at any rate as it will make the V4 merge smaller. I'm going to update this and ready it for merge.

**Comment by gmega** [comment]
Easy peasy lemon squeezy. :slightly_smiling_face:

**Review by gmega — APPROVED** [review]
LGTM!

**Comment by dryajov** [comment]
One thing that we should do, is just create a wrapper around the import and import that directly instead of explicitly importing chronos.

**Comment by gmega** [comment]
> One thing that we should do, is just create a wrapper around the import and import that directly instead of explicitly importing chronos.

You mean to shorten the path? As in a package alias so you don't have to type `pkg/asynctest/chronos/unittest`? I can do that, but not sure I prefer having to compute relative import paths in my head (as this would have to go under e.g. `/tests/asynctest.nim`) over typing a longer-but-always-the-same import line.

**Comment by gmega** [comment]
OK, I've updated it to use a wrapper, and it sort of confirms my point: IMHO it looks uglier, and it was an absolute pain to go through 40+ files and figure out the relative import path in each. I also ran into issues as Nim will import the wrong package if you do `import ./asynctest` but that relative path happens to be wrong (which doesn't happen when you import the package directly).

But now that it's done, the extra level of indirection will at least make it easier to swap the import in the referred package. I also don't anticipate this will be as painful when updating incrementally.

**Comment by markspanbroek** [comment]
Github won't let me approve because I started the PR, but feel free to merge at any time @gmega.

**Review by dryajov — APPROVED** [review]
LGTM

**Pull request merged**
