### PR TITLE
Remove moved docs

### PR DESCRIPTION
**Pull request by veaceslavdoina**
PR removes all the moved docs and updates main Readme file with the links to the new docs location - [new readme](https://github.com/codex-storage/nim-codex/tree/docs/remove-moved-docs).

We already moved all the docs to a documentation site - [docs.codex.storage](https://docs.codex.storage)

| File                                                                                                  | New location                                                                            | PR                                                  |
| ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- | --------------------------------------------------- |
| [`docs/DownloadFlow.md`](https://github.com/codex-storage/nim-codex/blob/master/docs/DownloadFlow.md) | [`learn/download-flow`](https://docs.codex.storage/learn/download-flow)                 | https://github.com/codex-storage/codex-docs/pull/29 |
| [`Marketplace.md`](https://github.com/codex-storage/nim-codex/blob/master/docs/Marketplace.md)        | [`learn/local-marketplace`](https://docs.codex.storage/learn/local-marketplace)         | https://github.com/codex-storage/codex-docs/pull/24 |
| [`TwoClientTest.md`](https://github.com/codex-storage/nim-codex/blob/master/docs/TwoClientTest.md)    | [`learn/local-two-client-test`](https://docs.codex.storage/learn/local-two-client-test) | https://github.com/codex-storage/codex-docs/pull/28 |

It was basically a copy/paste and in some cases with small adjustments. Please check mentioned PR's for more details.

### CODE REVIEW

**Comment by marcinczenko** [comment]
It is nice to have all the docs next to the code, but on the other there should be one source of true. What I am a bit concerned about is that the docs in the new documentation portal may change to be more "end-user-oriented" while the version that could be kept next to the code in the `nim-codex` repo could be more technical.

So I am ok with approving it, but I would like to see what people working longer than me with this repo are saying...

**Review by gmega — APPROVED** [review]
I agree with @marcinczenko on the one hand, but am fine with having this on docs for now. In particular the guides, I think they really belong there.

**Comment by AuHau** [comment]
I definitely agree with moving the docs folder, but I'm not sure if I like the removing of info's from the Readme. IMHO I would leave those info's there...

**Comment by veaceslavdoina** [comment]
> IMHO I would leave those info's there...

which one exactly?
- [Current readme](https://github.com/codex-storage/nim-codex/blob/master)
- [New readme](https://github.com/codex-storage/nim-codex/tree/docs/remove-moved-docs)
- [Current/new diff](https://github.com/codex-storage/nim-codex/pull/930/files)
- [Docs](https://docs.codex.storage/learn/run#configuration)

> [`### Environment variables`](https://github.com/codex-storage/nim-codex/blob/master/README.md#environment-variables)
> [`### Configuration file`](https://github.com/codex-storage/nim-codex/blob/master/README.md#configuration-file)
> [`### CLI Options`](https://github.com/codex-storage/nim-codex/blob/master/README.md#cli-options)
> [`#### Logging`](https://github.com/codex-storage/nim-codex/blob/master/README.md#logging)

CLI Options are outdated and does not reflect all the switches support. Good thing here is that they are not updated so often. People usually do not care about it - #687. Especially if you would like to update some lines in the main readme and it leads to the 2 approvals and ~ 2:30 hours CI.

Now I use `codex --help` as a reference.

[*docs.codex.storage*](https://docs.codex.storage) --> *Codex • Docs* --> *Run* - also not so long path.

Let me know and I can return just some chapters or everything updated.

**Review by benbierens — APPROVED** [review]

**Review by AuHau — APPROVED** [review]
Well, I was thinking that maybe updating the args will be easier in Readme compared to docs, but I guess it will be the same and actually we should definitely keep updated the docs compared this Readme, soooo - I withdraw my objection 😅

**Pull request merged**
