### PR TITLE
Create memory-leak detecting test suite

### PR DESCRIPTION
**Pull request by dryajov**
Expected to fail for now.

### CODE REVIEW

**Comment by Bulat-Ziganshin** [comment]
My task is to use these new checks to find memory leaks in stream usage

**Comment by dryajov** [comment]
We're also missing tests for `AsyncStreamWrapper`

**Comment by benbierens** [comment]
Renamed from 'Add chronos trackers'.

These changes now roll out the `checksuite`. This test suite automatically adds leak checking with Chronos to the tests. It verifies this by adding a tracker for `StoreStream`.
I would like to make new PRs for adding trackers to other modules in the future. New trackers should be added to `tests/helpers/trackers.nim` and they will be automatically checked by all the checksuites.

**Review by markspanbroek — APPROVED** [review]
:pray: Nice, thanks!

Not too sure about the name `checksuite`, perhaps use `trackersuite` or `tracksuite`? :runner:

**Comment by benbierens** [comment]
Merged by Dmitriy on 22 Jun 2023 20:01:21 +02:00

**Pull request merged**
