### PR TITLE
Initial support for nimble lock files

### PR DESCRIPTION
**Pull request by yyoncho**
- Add parallel ci-lock.yml
- In order to sync the lock file do the following:

``` bash
nimble lock --developFile=nimble-update-lock.develop
```

Note that --developFile support for lock is part of  this PR https://github.com/nim-lang/nimble/pull/1125 to be merged. If it is not merged, then you can rename nimble-update-lock.develop to nimble.develop and `nimble lock` will work just fine.

- I have used different `nim` version for the lock file because current `nim` does not have the proper nimble structure. I can bump the version in NBS if you want. I have also changed the versions of some of the packages in `vendor` folder to pass nimble version checks

### CODE REVIEW

**Comment by elcritch** [comment]
Looks good. There will be some conflicts with my PR to update the deps, but I can handle merging the conflicts. That should resolve the build errors you're seeing.

**Comment by elcritch** [comment]
@yyoncho I still have this in my work queue. It's just been bumped as I needed to work on some other things first.

**Comment by elcritch** [comment]
@dryajov mind reviewing this? It'd be nice to get Nimble running aside NBS.

**Comment by gmega** [comment]
I'm killing this as we've sort of embraced nimbus-build-system, so our lock files are the commit versions in the `/vendor` folder. Until package maintainers do proper versioning (so that the lockfile reflects one specific solution to dep constraints), I also don't see much of a win in using lockfiles as they are more complicated to deal with than submodules.

**Comment by dryajov** [comment]
Keep in mind that the plan is still to migrate to nimble and lockfiles, once we migrate to nim 2.0

**Pull request closed without merging**
